[package]
name = "blatann"
version = "0.1.0"
authors = ["thomas <thomas.gerstenberg@novoengineering.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrf_driver = {path = "../nrf_driver"}
